lens_name: lens_system2_mge

band: [F390W]

model:
  lens: [EPL, SHEAR_GAMMA_PSI]
  lens_light: [MGE_SET_ELLIPSE]
  source_light: [SHAPELETS]

lens_options:
  centroid_init: [0.04, -0.04]

lens_light_options:
  mge_config:
    0:
      n_comp: 20 # number of Gaussian components in the MGE set

source_light_options:
  n_max: [4] # array with n_max for each band

fitting:
  pso: true
  pso_settings:
    num_particle: 4
    num_iteration: 2

  sampling: false

numeric_options:
  supersampling_factor: [2]
